import { MaterialDetail } from '@/types/materials'

export const DEMO_MATERIALS: MaterialDetail[] = [
  {
    id: 'pet',
    name: 'PET',
    abbreviation: 'PET',
    category: 'plastic',
    moisture_barrier: 0.8,
    oxygen_barrier: 4.0,
    temp_min_c: -40,
    temp_max_c: 70,
    shelf_life_days: 730,
    eco_score: 42,
    recyclable: true,
    compostable: false,
    food_safe: true,
    cost_tier: 'low',
    description: 'Widely used food-grade plastic with excellent clarity and good barrier properties.',
    key_properties: ['Excellent clarity', 'Good moisture barrier', 'Recyclable', 'FDA approved'],
  },
  {
    id: 'hdpe',
    name: 'HDPE',
    abbreviation: 'HDPE',
    category: 'plastic',
    moisture_barrier: 0.3,
    oxygen_barrier: 150.0,
    temp_min_c: -50,
    temp_max_c: 120,
    shelf_life_days: 1095,
    eco_score: 45,
    recyclable: true,
    compostable: false,
    food_safe: true,
    cost_tier: 'low',
    description: 'Excellent moisture barrier, wide temperature range, suitable for dairy and juice.',
    key_properties: ['Excellent moisture barrier', 'Wide temperature range', 'Hot-fill suitable'],
  },
  {
    id: 'ldpe',
    name: 'LDPE',
    abbreviation: 'LDPE',
    category: 'plastic',
    moisture_barrier: 0.5,
    oxygen_barrier: 300.0,
    temp_min_c: -60,
    temp_max_c: 80,
    shelf_life_days: 365,
    eco_score: 30,
    recyclable: true,
    compostable: false,
    food_safe: true,
    cost_tier: 'low',
    description: 'Flexible plastic for films and bags. Good moisture but poor oxygen barrier.',
    key_properties: ['Flexible and soft', 'Heat sealable', 'Low cost'],
  },
  {
    id: 'pp',
    name: 'PP',
    abbreviation: 'PP',
    category: 'plastic',
    moisture_barrier: 0.4,
    oxygen_barrier: 80.0,
    temp_min_c: -20,
    temp_max_c: 135,
    shelf_life_days: 730,
    eco_score: 48,
    recyclable: true,
    compostable: false,
    food_safe: true,
    cost_tier: 'low',
    description: 'High heat resistance for hot-fill, microwave-safe, and retort packaging.',
    key_properties: ['Microwave safe', 'Heat resistant to 135°C', 'Retort suitable'],
  },
  {
    id: 'glass',
    name: 'Glass',
    abbreviation: 'Glass',
    category: 'glass',
    moisture_barrier: 0.0,
    oxygen_barrier: 0.0,
    temp_min_c: -40,
    temp_max_c: 300,
    shelf_life_days: 1825,
    eco_score: 72,
    recyclable: true,
    compostable: false,
    food_safe: true,
    cost_tier: 'medium',
    description: 'Absolute barrier material. Chemically inert, premium appearance, infinitely recyclable.',
    key_properties: ['Absolute oxygen barrier', 'Chemically inert', 'Premium appearance', 'Infinitely recyclable'],
  },
  {
    id: 'aluminum',
    name: 'Aluminum',
    abbreviation: 'Aluminum',
    category: 'metal',
    moisture_barrier: 0.0,
    oxygen_barrier: 0.0,
    temp_min_c: -60,
    temp_max_c: 200,
    shelf_life_days: 1825,
    eco_score: 65,
    recyclable: true,
    compostable: false,
    food_safe: true,
    cost_tier: 'medium',
    description: 'Total barrier to light, oxygen, and moisture. Ideal for long shelf life products.',
    key_properties: ['Total barrier', 'Light barrier', 'Retort suitable', 'Highly recyclable'],
  },
  {
    id: 'paperboard',
    name: 'Paperboard',
    abbreviation: 'Paperboard',
    category: 'paper',
    moisture_barrier: 15.0,
    oxygen_barrier: 500.0,
    temp_min_c: -20,
    temp_max_c: 120,
    shelf_life_days: 180,
    eco_score: 78,
    recyclable: true,
    compostable: true,
    food_safe: true,
    cost_tier: 'low',
    description: 'Sustainable, renewable, and compostable. Best for dry goods and short shelf life.',
    key_properties: ['Renewable', 'Compostable', 'High printability', 'Low cost'],
  },
  {
    id: 'pla',
    name: 'PLA',
    abbreviation: 'PLA',
    category: 'bio',
    moisture_barrier: 5.0,
    oxygen_barrier: 20.0,
    temp_min_c: -10,
    temp_max_c: 55,
    shelf_life_days: 365,
    eco_score: 82,
    recyclable: false,
    compostable: true,
    food_safe: true,
    cost_tier: 'high',
    description: 'Bio-based, industrially compostable. Good clarity. Temperature-limited.',
    key_properties: ['Bio-based', 'Industrially compostable', 'Good clarity', 'PET-like appearance'],
  },
  {
    id: 'pha',
    name: 'PHA',
    abbreviation: 'PHA',
    category: 'bio',
    moisture_barrier: 3.0,
    oxygen_barrier: 10.0,
    temp_min_c: -20,
    temp_max_c: 130,
    shelf_life_days: 730,
    eco_score: 92,
    recyclable: false,
    compostable: true,
    food_safe: true,
    cost_tier: 'premium',
    description: 'Home and industrially compostable bioplastic. Marine biodegradable. Premium cost.',
    key_properties: ['Home compostable', 'Marine biodegradable', 'Renewable feedstock', 'Superior eco-score'],
  },
  {
    id: 'multilayer',
    name: 'Multilayer',
    abbreviation: 'Multilayer',
    category: 'composite',
    moisture_barrier: 0.1,
    oxygen_barrier: 0.5,
    temp_min_c: -60,
    temp_max_c: 150,
    shelf_life_days: 1095,
    eco_score: 28,
    recyclable: false,
    compostable: false,
    food_safe: true,
    cost_tier: 'high',
    description: 'Exceptional barrier via combined materials. Maximum performance, minimum recyclability.',
    key_properties: ['Exceptional barrier', 'Extended shelf life', 'Retort suitable', 'Flexible'],
  },
]
